[package]
name = "memtest"
version = "0.1.0"
authors = ["kilb <git@bll.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.80"
